"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"project_id_env": "CROWDIN_PROJECT_ID"
"preserve_hierarchy": true
"files": [
  {
    "source": "/app/src/main/res/values/strings.xml",
    "dest": "/main_strings.xml",
    "translation": "/app/src/main/res/values-%android_code%/strings.xml",
    "languages_mapping": &stringmapping {
      "android_code": {
        "ar": "ar",
        "am": "am",
        "hy-AM": "hy-rAM",
        "az": "az",
        "be": "be",
        "bn": "bn-rBD",
        "bg": "bg",
        "ca": "ca",
        "cs": "cs",
        "da": "da",
        "de": "de",
        "el": "el",
        "es-ES": "es",
        "es-AR": "es-rAR",
        "es-MX": "es-rMX",
        "es-VE": "es-rVE",
        "et": "et-rEE",
        "eu": "eu-rES",
        "fa": "fa",
        "fil": "fil",
        "fi": "fi",
        "fr": "fr",
        "gl": "gl-rES",
        "hr": "hr",
        "hu": "hu",
        "is": "is",
        "id": "in",
        "it": "it",
        "he": "iw",
        "ja": "ja",
        "ka": "ka-rGE",
        "km": "km-rKH",
        "kn": "kn-rIN",
        "ko": "ko",
        "ky": "ky-rKG",
        "lt": "lt",
        "lv": "lv",
        "lo": "lo-rLA",
        "ms": "ms",
        "ml-IN": "ml-rIN",
        "mn": "mn-rMN",
        "mr": "mr-rIN",
        "my": "my-rMM",
        "ne-NP": "ne-rNP",
        "nl": "nl",
        "no": "nb",
        "pl": "pl",
        "pt-PT": "pt",
        "pt-BR": "pt-rBR",
        "ro": "ro",
        "ru": "ru",
        "rm-CH": "rm",
        "si-LK": "si-rLK",
        "sk": "sk",
        "sl": "sl",
        "sr": "sr",
        "sv-SE": "sv",
        "sw": "sw",
        "th": "th",
        "ta": "ta-rIN",
        "te": "te-rIN",
        "tr": "tr",
        "uk": "uk",
        "ur-IN": "ur-rIN",
        "uz": "uz",
        "vi": "vi",
        "zh-CN": "zh-rCN",
        "zh-HK": "zh-rHK",
        "zh-TW": "zh-rTW",
        "zu": "zu"
      }
    }
  },
  {
    "source": "/app/src/nonFree/res/values/strings.xml",
    "dest": "/nonFree_strings.xml",
    "translation": "/app/src/nonFree/res/values-%android_code%/strings.xml",
    "languages_mapping": *stringmapping
  }
]
