package dev.msfjarvis.aps.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006591)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFc7e6ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001e30)
val md_theme_light_secondary = Color(0xFF4f606e)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd3e5f5)
val md_theme_light_onSecondaryContainer = Color(0xFF0b1d29)
val md_theme_light_tertiary = Color(0xFF006494)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFc8e6ff)
val md_theme_light_onTertiaryContainer = Color(0xFF001e31)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcff)
val md_theme_light_onBackground = Color(0xFF1a1c1e)
val md_theme_light_surface = Color(0xFFfcfcff)
val md_theme_light_onSurface = Color(0xFF1a1c1e)
val md_theme_light_surfaceVariant = Color(0xFFdde3ea)
val md_theme_light_onSurfaceVariant = Color(0xFF41474d)
val md_theme_light_outline = Color(0xFF72787e)
val md_theme_light_inverseOnSurface = Color(0xFFf0f0f3)
val md_theme_light_inverseSurface = Color(0xFF2e3133)

val md_theme_dark_primary = Color(0xFF85ceff)
val md_theme_dark_onPrimary = Color(0xFF00344e)
val md_theme_dark_primaryContainer = Color(0xFF004c6f)
val md_theme_dark_onPrimaryContainer = Color(0xFFc7e6ff)
val md_theme_dark_secondary = Color(0xFFb7c9d9)
val md_theme_dark_onSecondary = Color(0xFF21323e)
val md_theme_dark_secondaryContainer = Color(0xFF384956)
val md_theme_dark_onSecondaryContainer = Color(0xFFd3e5f5)
val md_theme_dark_tertiary = Color(0xFF8aceff)
val md_theme_dark_onTertiary = Color(0xFF003450)
val md_theme_dark_tertiaryContainer = Color(0xFF004b70)
val md_theme_dark_onTertiaryContainer = Color(0xFFc8e6ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c1e)
val md_theme_dark_onBackground = Color(0xFFe1e2e5)
val md_theme_dark_surface = Color(0xFF1a1c1e)
val md_theme_dark_onSurface = Color(0xFFe1e2e5)
val md_theme_dark_surfaceVariant = Color(0xFF41474d)
val md_theme_dark_onSurfaceVariant = Color(0xFFc1c7ce)
val md_theme_dark_outline = Color(0xFF8b9197)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c1e)
val md_theme_dark_inverseSurface = Color(0xFFe1e2e5)

val seed = Color(0xFF003e5b)
val error = Color(0xFFba1b1b)
