name: Feature request
description: Suggest a new feature to be included in the app
title: "[FEATURE] "
labels: ["C-feature", "S-awaiting-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file this issue! Here are a few things to check before clicking the submit button :)
        1. Make sure you're on the latest version of the app. Features are being added all the time and it is entirely possible what you're requesting has already been added. The current release can be found here: https://github.com/android-password-store/android-password-store/releases/latest.
        2. Check the changelog file to confirm that the feature hasn't been added for an upcoming release: https://github.com/android-password-store/Android-Password-Store/blob/develop/CHANGELOG.md
        3. ALWAYS fill this template. If you fail to do so, your issue will be immediately closed with no response. Maintaining open source projects for free is hard work, and we expect users to respect that time and effort by putting in a little bit of their own. A feature request that is clear and explicit in its needs lets us get to work faster.

  - type: textarea
    id: feature-description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
