name: "Release nightly snapshots"
on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  deploy-release-snapshot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Decrypt secrets
      run: release/signing-setup.sh "$ENCRYPT_KEY"
      env:
        ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

    - uses: actions/cache@v1
      with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/dependencies.gradle') }}

    - name: Download gradle dependencies
      run: ./gradlew dependencies

    - name: Build release app
      run: ./gradlew :app:assembleRelease
      env:
        SNAPSHOT: "true"

    - name: Clean secrets
      run: release/signing-cleanup.sh

    - name: Deploy snapshot
      run: release/deploy-snapshot.sh
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
        SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
