on: push
name: CI builds
jobs:
  setup-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: setup-android
      uses: msfjarvis/setup-android@0.2
      with:
        gradleTasks: spotlessCheck build test lintDebug -Dpre-dex=false
