name: Update Publix Suffix List data
on:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  update-publicsuffix-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Download new publicsuffix data
        uses: burrunan/gradle-cache-action@03c71a8ba93d670980695505f48f49daf43704a6
        with:
          arguments: updatePSL

      - name: Compare list changes
        run: if [[ $(git diff --binary --stat) != '' ]]; then echo "UPDATED=true" >> $GITHUB_ENV; fi

      - name: Verify update publicsuffixes file
        uses: burrunan/gradle-cache-action@03c71a8ba93d670980695505f48f49daf43704a6
        if: env.UPDATED == 'true'
        with:
          arguments: :autofill-parser:test -PslimTests

      - name: Commit changes
        if: env.UPDATED == 'true'
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "noreply@github.com"
          git commit -am "autofill-parser: update publicsuffixes file"

      - name: Push to develop
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        if: env.UPDATED == 'true'
        with:
          github_token: ${{ secrets.PSL_UPDATE_TOKEN }}
          branch: develop
