name: Update Publix Suffix List data
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  update-publicsuffix-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Set up JDK
        uses: actions/setup-java@c3ac5dd0ed8db40fedb61c32fbe677e6b355e94c # v3.8.0
        with:
          distribution: temurin
          java-version: 18

      - name: Download new publicsuffix data
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2.3.3
        with:
          arguments: updatePSL
          gradle-home-cache-cleanup: true

      - name: Compare list changes
        run: if [[ $(git diff --binary --stat) != "" ]]; then echo "UPDATED=true" >> $GITHUB_ENV; fi

      - name: Verify update publicsuffixes file
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2.3.3
        if: "${{ env.UPDATED == 'true' }}"
        with:
          arguments: :autofill-parser:test -PslimTests
          gradle-home-cache-cleanup: true

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04 # v4.2.3
        if: "${{ env.UPDATED == 'true' }}"
        with:
          author: GitHub Actions <noreply@github.com>
          base: develop
          body: This is an automated pull request to update the publicsuffixes file to the latest copy from Mozilla
          branch: bot/update-psl
          commit-message: "autofill-parser: update publicsuffixes file"
          labels: A-PSL, S-automerge
          title: Update Public Suffix List data
          token: ${{ secrets.PSL_UPDATE_TOKEN }}

      - name: Enable automerge for PR
        if: "${{ steps.cpr.outputs.pull-request-operation == 'created' }}"
        shell: bash
        run: |
          gh pr merge --squash --auto "${PR_URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.PSL_UPDATE_TOKEN }}
          PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
