name: Update Publix Suffix List data
on:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  update-publicsuffix-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download new publicsuffix data
        run: curl -L https://github.com/mozilla-mobile/android-components/raw/master/components/lib/publicsuffixlist/src/main/assets/publicsuffixes -o app/src/main/assets/publicsuffixes

      - name: Compare list changes
        run: if [[ $(git diff --binary --stat) != '' ]]; then echo "::set-env name=UPDATED::true"; fi

      - name: Commit changes
        if: env.UPDATED == 'true'
        run: |
          git checkout -b bot/update-psl
          git add app/src/main/assets/publicsuffixes
          git commit --message "Update Public Suffix List data"

      - name: Create update PR
        uses: thomaseizinger/create-pull-request@1.0.0
        if: env.UPDATED == 'true'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: bot/update-psl
          base: develop
          title: 'Update Public Suffix List data'
          body: 'Updates Public Suffix List from https://publicsuffix.org/list/'
