name: Update Publix Suffix List data
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  update-publicsuffix-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1

      - name: Set up JDK
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          distribution: temurin
          java-version: 18

      - name: Download new publicsuffix data
        uses: gradle/gradle-build-action@6095a76664413da4c8c134ee32e8a8ae900f0f1f # v2.4.0
        with:
          arguments: updatePSL
          gradle-home-cache-cleanup: true

      - name: Check if PR is required
        run: if [[ $(git status -s) != '' ]]; then echo "UPDATED=true" >> $GITHUB_ENV; fi

      - name: Verify update publicsuffixes file
        uses: gradle/gradle-build-action@6095a76664413da4c8c134ee32e8a8ae900f0f1f # v2.4.0
        if: "${{ env.UPDATED == 'true' }}"
        with:
          arguments: :autofill-parser:test -PslimTests
          gradle-home-cache-cleanup: true

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@5b4a9f6a9e2af26e5f02351490b90d01eb8ec1e5 # v5.0.0
        if: "${{ env.UPDATED == 'true' }}"
        with:
          author: GitHub Actions <noreply@github.com>
          base: develop
          body: This is an automated pull request to update the publicsuffixes file to the latest copy from Mozilla
          branch: bot/update-psl
          commit-message: "autofill-parser: update publicsuffixes file"
          labels: A-PSL, S-automerge
          title: Update Public Suffix List data
          token: ${{ secrets.PSL_UPDATE_TOKEN }}

      - name: Enable automerge for PR
        if: "${{ steps.cpr.outputs.pull-request-operation == 'created' }}"
        shell: bash
        run: |
          gh pr merge --squash --auto "${PR_URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.PSL_UPDATE_TOKEN }}
          PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
