name: Update Publix Suffix List data
on:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  update-publicsuffix-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c952173edf28a2bd22e1a4926590c1ac39630461

      - name: Download new publicsuffix data
        run: curl -L https://github.com/mozilla-mobile/android-components/raw/master/components/lib/publicsuffixlist/src/main/assets/publicsuffixes -o autofill-parser/src/main/assets/publicsuffixes

      - name: Compare list changes
        run: if [[ $(git diff --binary --stat) != '' ]]; then echo "UPDATED=true" >> $GITHUB_ENV; fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c7f493a8000b8aeb17a1332e326ba76b57cb83eb
        if: env.UPDATED == 'true'
        with:
          assignees: msfjarvis
          author: GitHub Actions <noreply@github.com>
          base: develop
          body: This is an automated pull request to update the publicsuffixes file to the latest copy from Mozilla
          branch: bot/update-psl
          commit-message: "autofill-parser: update publicsuffixes file"
          labels: PSL
          title: Update Public Suffix List data
          token: ${{ secrets.GITHUB_TOKEN }}
