name: Update Publix Suffix List data
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  update-publicsuffix-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up JDK
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: temurin
          java-version: 20

      - name: Download new publicsuffix data
        uses: gradle/gradle-build-action@8cbcb9948b5892387aed077daf6f90e1f0ba5b27 # v2.11.0
        with:
          arguments: updatePSL
          gradle-home-cache-cleanup: true

      - name: Check if PR is required
        run: if [[ $(git status -s) != '' ]]; then echo "UPDATED=true" >> $GITHUB_ENV; fi

      - name: Verify update publicsuffixes file
        uses: gradle/gradle-build-action@8cbcb9948b5892387aed077daf6f90e1f0ba5b27 # v2.11.0
        if: "${{ env.UPDATED == 'true' }}"
        with:
          arguments: :autofill-parser:test -PslimTests
          gradle-home-cache-cleanup: true

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        if: "${{ env.UPDATED == 'true' }}"
        with:
          author: GitHub Actions <noreply@github.com>
          base: develop
          body: This is an automated pull request to update the publicsuffixes file to the latest copy from Mozilla
          branch: bot/update-psl
          commit-message: "autofill-parser: update publicsuffixes file"
          labels: A-PSL, S-automerge
          title: Update Public Suffix List data
          token: ${{ secrets.PSL_UPDATE_TOKEN }}

      - name: Enable automerge for PR
        if: "${{ steps.cpr.outputs.pull-request-operation == 'created' }}"
        shell: bash
        run: |
          gh pr merge --squash --auto "${PR_URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.PSL_UPDATE_TOKEN }}
          PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
