name: Update Publix Suffix List data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  update-publicsuffix-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Set up JDK
        uses : actions/setup-java@v2.4.0
        with :
          distribution : 'zulu'
          java-version : '17'
          cache: 'gradle'

      - name: Download new publicsuffix data
        uses: gradle/gradle-build-action@v2.1.0
        with:
          arguments: updatePSL

      - name: Compare list changes
        run: if [[ $(git diff --binary --stat) != '' ]]; then echo "UPDATED=true" >> $GITHUB_ENV; fi

      - name: Verify update publicsuffixes file
        uses: gradle/gradle-build-action@v2.1.0
        if: env.UPDATED == 'true'
        with:
          arguments: :autofill-parser:test -PslimTests

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3.12.0
        if: env.UPDATED == 'true'
        with:
          assignees: msfjarvis
          author: GitHub Actions <noreply@github.com>
          base: develop
          body: This is an automated pull request to update the publicsuffixes file to the latest copy from Mozilla
          branch: bot/update-psl
          commit-message: "autofill-parser: update publicsuffixes file"
          labels: A-PSL
          title: Update Public Suffix List data
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Close, re-open and enable squash merge for PR
        if: steps.cpr.outputs.pull-request-operation == 'created'
        shell: bash
        run: |
          gh pr close "${PR_URL}"
          gh pr reopen "${PR_URL}"
          gh pr merge --squash --auto "${PR_URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.PSL_UPDATE_TOKEN }}
          PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
