name: "Validate Gradle Wrapper"
on:
  pull_request:
    paths:
      - '.github/**'
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'

jobs:
  validation:
    name: "Wrapper validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
